@startuml ゲーム時のアクティビティ図
    |TitleScene|
    start
    :タイトル表示;
    :ゲーム開始を選択(ボタンをクリックする);

    |GameScene|
    :カウントダウンが始まる;
    :カウントダウン終了;
    :タイマースタート;
    :プレイヤーはクリックする;
    :タイマーストップ;
    :結果を表示;
    :結果が表示された状態でスペース;

    |TitleScene|
    :タイトル表示;
    stop
@enduml