@startuml GameSceneクラス図

namespace Managers{
    enum Phase{
        REDY,
        GAME,
        RESULT,
        END
    }

    class PhaseManager{
        +getPhase()
    }

    class Initarizer{
        +init()
    }

    Phase --o PhaseManager
    Initarizer --> PhaseManager
}


namespace Scores{
    class ScoreData<<stract>>{
        +int count
    }

    class ScoreCounter<<singleton>>{
        +setInput(IInputEventProvider)
    }

    ScoreCounter --> Inputs.IInputEventProvider:obsever
    ScoreData -left-o ScoreCounter

    ScoreCounter --> Rankings.RankingManager
    ScoreCounter -left-> Managers.PhaseManager
}


namespace Timers{
    class TimerPresenter{

    }

    class TimerView<<singleton>>{

    }
    class CountDownView<<singleton>>{

    }

    class Timer<<abstract>>{
        +stertTimer
        +endTimer
    }

    TimerView --|> Timer
    CountDownView --|> Timer

    TimerPresenter <-right-> Managers.PhaseManager:Obsever
    TimerPresenter o-right-> Timer:Obsever

}


namespace Inputs{
    class GameInputsEventProvider<<SingletonMono>>{

    }

    interface IInputEventProvider{
    }

    GameInputsEventProvider .right.|> IInputEventProvider
}


namespace Rankings{
    class RankingManager <<singleton>>{
        -RankingData data
        +getRanking()
        -wrightRanking()
        +updateRanking(int)
    }

    class RankingData<<stract>>{
        +int rank1
        +int rank2
        +int rank3
    }

    RankingManager o-- RankingData 
}

@enduml