@startuml GameSceneクラス図

package Managers{
    class PhaseManager{

    }

    class InputManager{

    }

    class RankingManager{

    }
}

package Scores{
    class ScoreData<<stract>>{
        +int count
    }

    class ScoreCounter{

    }
}

package Timers{
    class TimerManager{

    }
}

package Inputs{
    class gameInputsEventProvider{

    }

    interface IInputEventProvider{
    }
}

@enduml